# Numpy

In [ ]:
# Its faster than normal list
# uses less space
#mathlab replacement
#plotting matplotlib
#backend (pandas,connect 4, digital photography)
#machine learning

In [ ]:
#import numpy
import numpy as np

# Basics

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(a)

In [ ]:
#two dimensional array
b = np.array([[1,2,3,4],[5,7,8,9]])
print(b)

In [ ]:

c = np.array([[1,2,3],[4,5,6],[7,8,9] ])
print(c)

In [ ]:
#get dimension of array
a.ndim

In [ ]:
b.ndim

In [ ]:
c.ndim

In [ ]:
#get shape
b.shape

In [ ]:
c.shape

In [ ]:
#get type
a.dtype

In [ ]:
b.dtype

In [ ]:
c.dtype

In [ ]:
#Get size
a.itemsize

In [ ]:
b.itemsize

In [ ]:
#total size
a.size


In [ ]:
b.size

In [ ]:
# Accessing and changing rows and colums

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
a.shape
print(a)

In [ ]:

#get specific element [r,c]
a[1,5]

In [ ]:
a[1,-2]

In [ ]:
#get specifc row
a[1]

In [ ]:
a[0]

In [ ]:
a[0:2,1:3]

In [ ]:
a

In [ ]:
a[:,2]

In [ ]:
#Getting a lttle more fancy a[startindex:endindex:step]
a[0,2:6:2]


In [ ]:
#change values
a[1,5]

In [ ]:
a[1,5]=12

In [ ]:
a

In [ ]:
a[:,2]=5

In [ ]:
a

In [ ]:
a[:,2]=[1,2]

In [ ]:
a

In [ ]:
b=np.array([[[1,2],[2,4]],[[5,6],[7,8]]])

In [ ]:
b

In [ ]:
#get specific element (work outside in)
b[0,1,1]

In [ ]:
b[0,1]

In [ ]:
b[[0,1],[1,0]]

In [ ]:
#replace

b[:,1,:]=[8,8]

In [ ]:
b

# Initializing different types of array

In [ ]:
# All 0s matrix
np.zeros((4))

In [ ]:
np.zeros((2,3))

In [ ]:
np.zeros((2,3,2))

In [ ]:
np.zeros((2,3,5))

In [ ]:
np.ones((2,3,2))

In [ ]:
#any number
np.full((2,2),99)

In [ ]:
np.full((2,2),99, dtype='float32')

In [ ]:
#any number of dull like
np.full(a.shape,4)

In [ ]:
np.full_like(a.shape,4)

In [ ]:
#array of random numbers
np.random.rand(4,2)

In [ ]:
np.random.random_sample(a.shape)

In [ ]:
#random interger values
np.random.randint(1, size=(3,3))

In [ ]:
#the identity matrix
np.identity(3)

In [ ]:
#repeat array
arr=np.array([[1,2,3]])
r1 =np.repeat(arr,3,axis=0)
print (r1)

In [ ]:
s = np.ones((5,5))

In [ ]:
s

In [ ]:
s[1,1:4]=[0]

In [ ]:
s

In [ ]:
s[2,1:3:1]=[0]

In [ ]:
s

In [ ]:
s[3,1:4]=[0]

In [ ]:
s

In [ ]:
s[2,2]=9

In [ ]:
s

In [ ]:
s[2,3]=1

In [ ]:
s

In [ ]:
output = np.ones((5,5))

In [130]:
z=np.zeros((3,3))

In [132]:
z[1,1] = 9
output[1:4,1:4] = z

In [133]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [136]:
# Be careful when copying arrays
a=np.array([1,2,3])
b=a
b[0]=100

In [137]:
b

array([100,   2,   3])

In [138]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100

In [139]:
b

array([100,   2,   3])

# Mathematics

In [140]:
a+2

array([3, 4, 5])

In [141]:
a

array([1, 2, 3])

In [142]:
a*2

array([2, 4, 6])

In [143]:
a/2

array([0.5, 1. , 1.5])

In [144]:
a+2

array([3, 4, 5])

In [147]:
a =np.array([1,2,3,4])
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [149]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [150]:
#take sign of all values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [156]:
a=np.ones((2,3))

b=np.full((3,2),2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [157]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [158]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [159]:
#find the determinant
c =np.identity(3)
np.linalg.det(c)

1.0

In [160]:
# Statistics with numpy

In [161]:
stats =np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
np.min(stats)

1

In [163]:
np.max(stats)

6

In [164]:
np.max(stats,axis=1)

array([3, 6])

In [165]:
np.sum(stats)

21

In [166]:
np.sum(stats,axis=1)

array([ 6, 15])

In [168]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [169]:
# Reorganising Arrays

In [170]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [174]:
after=before.reshape((2,2,2))
print (after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [177]:
#Vertically stacking Vectors(matrix)

v1=np.array([1,2,3,4])

v2=np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [178]:


np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [179]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [180]:
# Miscellaneous

In [190]:
#load data from file
filedata=np.genfromtxt('data.txt', delimiter=',')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [189]:
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [192]:
filedata=filedata.astype('int32')

In [194]:
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Advanced indexing
## boolean masking and indexing

In [195]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [196]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [202]:
## index can be done with a list in numpy

a =np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [205]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [207]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [210]:
((filedata >50) & (filedata <100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [211]:
(~(filedata >50) & (filedata <100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [212]:
a[2,0:1,3,0:1]

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed